export enum DocumentType {
  INVOICE = 'INVOICE',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  TENANT_CREDIT_RECEIPT = 'TENANT_CREDIT_RECEIPT',
  LEASE_CONTRACT = 'LEASE_CONTRACT',
  MAINTENANCE_REPORT = 'MAINTENANCE_REPORT',
}
