ALTER TABLE buildings ADD COLUMN IF NOT EXISTS state VARCHAR(40) NOT NULL DEFAULT 'EXPLOITED';
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS commune VARCHAR(120);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS floors_count INTEGER;
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS total_units INTEGER;
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS manager_name VARCHAR(160);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS manager_phone VARCHAR(60);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS manager_email VARCHAR(160);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS observations TEXT;

UPDATE buildings
SET state = 'EXPLOITED'
WHERE state IS NULL OR state = '';
