type CanonicalRole = 'ADMIN' | 'EDITOR' | 'VIEWER';

const editorPermissions = [
  'dashboard.read',
  'activity.read',
  'buildings.read',
  'buildings.create',
  'buildings.update',
  'units.read',
  'units.create',
  'units.update',
  'tenants.read',
  'tenants.create',
  'tenants.update',
  'leases.read',
  'leases.create',
  'leases.update',
  'leases.delete',
  'leases.trash.read',
  'leases.restore',
  'leases.hard_delete',
  'leases.archive',
  'leases.archives.read',
  'invoices.read',
  'invoices.create',
  'invoices.update',
  'payments.read',
  'payments.create',
  'payments.update',
  'payments.delete',
  'bank_accounts.read',
  'bank_accounts.create',
  'bank_accounts.update',
  'bank_transactions.read',
  'treasury_transfers.read',
  'treasury_transfers.create',
  'treasury_transfers.from_cash',
  'treasury_transfers.from_bank',
  'treasury_transfers.bank_to_bank',
  'shareholders.read',
  'shareholders.create',
  'shareholders.update',
  'shareholder_payouts.read',
  'shareholder_payouts.create',
  'shareholder_payouts.delete',
  'shareholder_payouts.receipt',
  'shareholder_payouts.export',
  'shareholder_payouts.from_guarantee_cash',
  'shareholder_payouts.from_bank',
  'tenant_credits.refund',
  'tenant_credits.cancel',
  'cash.read',
  'cash.create',
  'cash.update',
  'cash_movements.delete',
  'cash.close',
  'guarantee_cash.read',
  'guarantee_cash.create',
  'guarantee_cash.delete',
  'guarantee_cash.expense',
  'guarantee_cash.export',
  'stock.read',
  'stock.create',
  'stock.update',
  'stock.receive',
  'stock.inventory',
  'maintenance.read',
  'maintenance.create',
  'maintenance.update',
  'maintenance.assign',
  'maintenance.validate',
  'maintenance.close',
  'maintenance.report',
  'staff.read',
  'staff.create',
  'staff.update',
  'payroll.read',
  'payroll.create',
  'payroll.update',
  'documents.read',
  'documents.upload',
  'communication.read',
  'communication.update',
  'communication.test',
  'communication.send',
  'communication.logs',
  'communication.logs.read',
  'notifications.read',
  'notifications.update',
  'automations.read',
  'reports.read',
  'reports.export',
  'workflow.read',
  'workflow.create',
  'workflow.approve',
  'workflow.reject',
];

const viewerPermissions = [
  'dashboard.read',
  'activity.read',
  'buildings.read',
  'units.read',
  'tenants.read',
  'leases.read',
  'leases.trash.read',
  'leases.archives.read',
  'invoices.read',
  'payments.read',
  'bank_accounts.read',
  'bank_transactions.read',
  'treasury_transfers.read',
  'shareholders.read',
  'shareholder_payouts.read',
  'shareholder_payouts.receipt',
  'shareholder_payouts.export',
  'cash.read',
  'guarantee_cash.read',
  'guarantee_cash.export',
  'stock.read',
  'maintenance.read',
  'maintenance.report',
  'staff.read',
  'documents.read',
  'communication.read',
  'communication.logs',
  'communication.logs.read',
  'notifications.read',
  'notifications.update',
  'automations.read',
  'reports.read',
  'reports.export',
  'settings.read',
  'reference_data.read',
  'publisher_settings.read',
  'workflow.read',
];

const additionalPermissions = [
  'tenant_credits.update',
  'sales.read',
  'sales.admin',
  'sales.settings.read',
  'sales.settings.manage',
  'sales_buyers.read',
  'sales_buyers.create',
  'sales_buyers.update',
  'sales_buyers.archive',
  'sales_projects.read',
  'sales_projects.create',
  'sales_projects.update',
  'sales_projects.archive',
  'sales_catalog.read',
  'sales_catalog.create',
  'sales_catalog.update',
  'sales_catalog.archive',
  'sales_reservations.read',
  'sales_reservations.create',
  'sales_reservations.update',
  'sales_reservations.cancel',
  'sales_reservations.approve',
  'sales_subscriptions.read',
  'sales_subscriptions.create',
  'sales_subscriptions.update',
  'sales_subscriptions.approve',
  'sales_subscriptions.cancel',
  'sales_contracts.read',
  'sales_contracts.create',
  'sales_contracts.update',
  'sales_contracts.approve',
  'sales_schedules.read',
  'sales_schedules.create',
  'sales_schedules.update',
  'sales_payments.read',
  'sales_payments.create',
  'sales_payments.allocate',
  'sales_payments.cancel',
  'sales_payments.refund',
  'sales_invoices.read',
  'sales_invoices.create',
  'sales_invoices.update',
  'sales_invoices.cancel',
  'sales_invoices.send',
  'sales_reports.balance',
  'sales_reservation_payments.read',
  'sales_reservation_payments.create',
  'sales_reservation_payments.cancel',
  'sales_reservation_payments.refund',
  'sales_reservation_receipts.read',
  'sales_reservation_receipts.generate',
  'sales_recovery.read',
  'sales_recovery.create',
  'sales_documents.read',
  'sales_documents.create',
  'sales_documents.generate',
  'sales_documents.regenerate',
  'sales_documents.sign',
  'sales_documents.download',
  'sales_templates.read',
  'sales_templates.manage',
  'sales_reports.read',
];

const salesManagerPermissions = [...additionalPermissions];

const salesAgentPermissions = [
  'sales.read',
  'sales_buyers.read',
  'sales_buyers.create',
  'sales_buyers.update',
  'sales_projects.read',
  'sales_catalog.read',
  'sales_reservations.read',
  'sales_reservations.create',
  'sales_reservations.update',
  'sales_subscriptions.read',
  'sales_subscriptions.create',
  'sales_subscriptions.update',
  'sales_invoices.read',
  'sales_invoices.create',
  'sales_invoices.update',
  'sales_contracts.read',
  'sales_contracts.create',
  'sales_documents.read',
  'sales_documents.generate',
];

const salesAccountantPermissions = [
  'sales.read',
  'sales_buyers.read',
  'sales_projects.read',
  'sales_catalog.read',
  'sales_reservations.read',
  'sales_subscriptions.read',
  'sales_schedules.read',
  'sales_payments.read',
  'sales_payments.create',
  'sales_payments.cancel',
  'sales_payments.refund',
  'sales_invoices.read',
  'sales_invoices.create',
  'sales_invoices.update',
  'sales_invoices.cancel',
  'sales_invoices.send',
  'sales_reports.balance',
  'sales_reservation_payments.read',
  'sales_reservation_payments.create',
  'sales_reservation_payments.refund',
  'sales_reservation_receipts.read',
  'sales_reservation_receipts.generate',
  'sales_recovery.read',
  'sales_reports.read',
  'sales_documents.read',
];

const salesViewerPermissions = [
  'sales.read',
  'sales_buyers.read',
  'sales_projects.read',
  'sales_catalog.read',
  'sales_reservations.read',
  'sales_subscriptions.read',
  'sales_invoices.read',
  'sales_payments.read',
  'sales_reports.balance',
  'sales_reports.read',
  'sales_documents.read',
  'sales_reservation_payments.read',
  'sales_reservation_receipts.read',
];

export const ROLE_ALIASES: Record<string, CanonicalRole> = {
  SUPER_ADMIN: 'ADMIN',
  ADMIN: 'ADMIN',
  ADMIN_PLATFORM: 'ADMIN',
  ADMIN_CLIENT: 'ADMIN',
  EDITOR: 'EDITOR',
  EDITOR_CLIENT: 'EDITOR',
  VIEWER: 'VIEWER',
  VIEWER_CLIENT: 'VIEWER',
  ACCOUNTANT: 'EDITOR',
  STAFF: 'EDITOR',
  AGENT: 'EDITOR',
  GESTIONNAIRE: 'EDITOR',
  COMPTABLE: 'EDITOR',
  DIRECTOR: 'VIEWER',
  DIRECTEUR: 'VIEWER',
  SALES_MANAGER: 'EDITOR',
  SALES_AGENT: 'EDITOR',
  SALES_ACCOUNTANT: 'VIEWER',
  SALES_VIEWER: 'VIEWER',
};

export const ROLE_LABELS: Record<string, string> = {
  SUPER_ADMIN: 'Super administrateur',
  ADMIN: 'Administrateur plateforme',
  ADMIN_PLATFORM: 'Administrateur plateforme',
  ADMIN_CLIENT: 'Administrateur client',
  EDITOR: 'Utilisateur en écriture',
  EDITOR_CLIENT: 'Utilisateur en écriture',
  VIEWER: 'Lecture seule',
  VIEWER_CLIENT: 'Lecture seule',
  ACCOUNTANT: 'Utilisateur en écriture',
  STAFF: 'Utilisateur en écriture',
  AGENT: 'Utilisateur en écriture',
  GESTIONNAIRE: 'Utilisateur en écriture',
  COMPTABLE: 'Utilisateur en écriture',
  DIRECTOR: 'Lecture seule',
  DIRECTEUR: 'Lecture seule',
  SALES_MANAGER: 'Manager commercial',
  SALES_AGENT: 'Agent commercial',
  SALES_ACCOUNTANT: 'Comptable commercial',
  SALES_VIEWER: 'Lecture commerciale',
};

export function normalizeRole(role?: string | null): CanonicalRole {
  const candidate = String(role ?? '').toUpperCase();
  return ROLE_ALIASES[candidate] ?? 'VIEWER';
}

export function roleDisplayName(role?: string | null) {
  const value = String(role ?? '').toUpperCase();
  return ROLE_LABELS[value] ?? ROLE_LABELS[normalizeRole(role)];
}

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ['*'],
  ADMIN: ['*'],
  ADMIN_PLATFORM: ['*'],
  ADMIN_CLIENT: ['*'],
  EDITOR: editorPermissions,
  EDITOR_CLIENT: editorPermissions,
  VIEWER: viewerPermissions,
  VIEWER_CLIENT: viewerPermissions,
  ACCOUNTANT: editorPermissions,
  STAFF: editorPermissions,
  AGENT: editorPermissions,
  GESTIONNAIRE: editorPermissions,
  COMPTABLE: editorPermissions,
  DIRECTOR: viewerPermissions,
  DIRECTEUR: viewerPermissions,
  SALES_MANAGER: salesManagerPermissions,
  SALES_AGENT: salesAgentPermissions,
  SALES_ACCOUNTANT: salesAccountantPermissions,
  SALES_VIEWER: salesViewerPermissions,
};

export const PERMISSIONS = Array.from(
  new Set([
    ...Object.values(ROLE_PERMISSIONS).flat().filter((item) => item !== '*'),
    ...additionalPermissions,
  ]),
);

export function permissionSetForRole(role?: string | null) {
  const value = String(role ?? '').toUpperCase();
  return ROLE_PERMISSIONS[value] ?? ROLE_PERMISSIONS[normalizeRole(role)] ?? [];
}

export function isPlatformRole(role?: string | null) {
  const value = String(role ?? '').toUpperCase();
  return value === 'SUPER_ADMIN' || value === 'ADMIN' || value === 'ADMIN_PLATFORM';
}
