export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: ['*'],
  ACCOUNTANT: [
    'dashboard.read',
    'activity.read',
    'invoices.read',
    'invoices.create',
    'invoices.update',
    'payments.read',
    'payments.create',
    'payments.update',
    'payments.delete',
    'cash.read',
    'cash.create',
    'cash.update',
    'cash.close',
    'reports.read',
    'reports.export',
    'stock.read',
    'maintenance.read',
    'maintenance.report',
    'communication.read',
    'communication.send',
    'communication.logs.read',
    'notifications.read',
    'notifications.update',
    'settings.read',
    'reference_data.read',
    'workflow.read',
    'workflow.create',
    'staff.read',
    'staff.create',
    'staff.update',
    'payroll.read',
    'payroll.create',
    'payroll.update',
    'workflow.read',
    'workflow.create',
  ],
  STAFF: [
    'dashboard.read',
    'activity.read',
    'buildings.read',
    'buildings.create',
    'buildings.update',
    'units.read',
    'units.create',
    'units.update',
    'tenants.read',
    'tenants.create',
    'tenants.update',
    'invoices.read',
    'invoices.create',
    'payments.read',
    'payments.create',
    'payments.update',
    'documents.read',
    'documents.upload',
    'maintenance.read',
    'maintenance.create',
    'maintenance.update',
    'maintenance.assign',
    'communication.read',
    'communication.send',
    'notifications.read',
    'notifications.update',
    'settings.read',
    'reference_data.read',
    'workflow.read',
    'workflow.create',
  ],
  DIRECTOR: ['dashboard.read', 'activity.read', 'reports.read', 'reports.export', 'buildings.read', 'units.read', 'tenants.read', 'invoices.read', 'payments.read', 'cash.read', 'stock.read', 'staff.read', 'documents.read', 'maintenance.read', 'maintenance.report', 'communication.read', 'communication.logs.read', 'notifications.read', 'notifications.update', 'settings.read', 'reference_data.read', 'publisher_settings.read', 'workflow.read', 'workflow.approve', 'workflow.reject'],
};

export const PERMISSIONS = Array.from(new Set(Object.values(ROLE_PERMISSIONS).flat().filter((item) => item !== '*')));
